service: order-consumers
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1


plugins:
  - serverless-pseudo-parameters

functions:
  orderCreatedConsumer1:
    handler: lambdaconsumer1/handler.orderCreatedConsumer1
    events:
    - sns: "arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:orderCreated" 
  
resources:
 Resources:
    OrdersDeadLetterQueue: 
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: OrdersDeadLetterQueue
    SNSSQSPermission:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Id: MyQueuePolicy
          Version: '2012-10-17'
          Statement:
          - Sid: Allow-SNS
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - sqs:SendMessage 
            Resource: "*"
        Queues: 
          - !Ref OrdersDeadLetterQueue